# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_payment_python_sdk import schemas  # noqa: F401


class NetAmountBreakdownItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def payable_amount() -> typing.Type['Money']:
                return Money
        
            @staticmethod
            def converted_amount() -> typing.Type['Money']:
                return Money
        
            @staticmethod
            def exchange_rate() -> typing.Type['ExchangeRate']:
                return ExchangeRate
            __annotations__ = {
                "payable_amount": payable_amount,
                "converted_amount": converted_amount,
                "exchange_rate": exchange_rate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payable_amount"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["converted_amount"]) -> 'Money': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["exchange_rate"]) -> 'ExchangeRate': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["payable_amount", "converted_amount", "exchange_rate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payable_amount"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["converted_amount"]) -> typing.Union['Money', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["exchange_rate"]) -> typing.Union['ExchangeRate', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payable_amount", "converted_amount", "exchange_rate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        payable_amount: typing.Union['Money', schemas.Unset] = schemas.unset,
        converted_amount: typing.Union['Money', schemas.Unset] = schemas.unset,
        exchange_rate: typing.Union['ExchangeRate', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NetAmountBreakdownItem':
        return super().__new__(
            cls,
            *args,
            payable_amount=payable_amount,
            converted_amount=converted_amount,
            exchange_rate=exchange_rate,
            _configuration=_configuration,
            **kwargs,
        )

from pay_pal_payment_python_sdk.model.exchange_rate import ExchangeRate
from pay_pal_payment_python_sdk.model.money import Money
