# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_payment_python_sdk import schemas  # noqa: F401


class ProcessorResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The processor response information for payment requests, such as direct credit card transactions.
    """


    class MetaOapg:
        
        class properties:
            
            
            class avs_code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def A(cls):
                    return cls("A")
                
                @schemas.classproperty
                def B(cls):
                    return cls("B")
                
                @schemas.classproperty
                def C(cls):
                    return cls("C")
                
                @schemas.classproperty
                def D(cls):
                    return cls("D")
                
                @schemas.classproperty
                def E(cls):
                    return cls("E")
                
                @schemas.classproperty
                def F(cls):
                    return cls("F")
                
                @schemas.classproperty
                def G(cls):
                    return cls("G")
                
                @schemas.classproperty
                def I(cls):
                    return cls("I")
                
                @schemas.classproperty
                def M(cls):
                    return cls("M")
                
                @schemas.classproperty
                def N(cls):
                    return cls("N")
                
                @schemas.classproperty
                def P(cls):
                    return cls("P")
                
                @schemas.classproperty
                def R(cls):
                    return cls("R")
                
                @schemas.classproperty
                def S(cls):
                    return cls("S")
                
                @schemas.classproperty
                def U(cls):
                    return cls("U")
                
                @schemas.classproperty
                def W(cls):
                    return cls("W")
                
                @schemas.classproperty
                def X(cls):
                    return cls("X")
                
                @schemas.classproperty
                def Y(cls):
                    return cls("Y")
                
                @schemas.classproperty
                def Z(cls):
                    return cls("Z")
                
                @schemas.classproperty
                def NULL(cls):
                    return cls("Null")
                
                @schemas.classproperty
                def POSITIVE_0(cls):
                    return cls("0")
                
                @schemas.classproperty
                def POSITIVE_1(cls):
                    return cls("1")
                
                @schemas.classproperty
                def POSITIVE_2(cls):
                    return cls("2")
                
                @schemas.classproperty
                def POSITIVE_3(cls):
                    return cls("3")
                
                @schemas.classproperty
                def POSITIVE_4(cls):
                    return cls("4")
            
            
            class cvv_code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def E(cls):
                    return cls("E")
                
                @schemas.classproperty
                def I(cls):
                    return cls("I")
                
                @schemas.classproperty
                def M(cls):
                    return cls("M")
                
                @schemas.classproperty
                def N(cls):
                    return cls("N")
                
                @schemas.classproperty
                def P(cls):
                    return cls("P")
                
                @schemas.classproperty
                def S(cls):
                    return cls("S")
                
                @schemas.classproperty
                def U(cls):
                    return cls("U")
                
                @schemas.classproperty
                def X(cls):
                    return cls("X")
                
                @schemas.classproperty
                def ALL_OTHERS(cls):
                    return cls("All others")
                
                @schemas.classproperty
                def POSITIVE_0(cls):
                    return cls("0")
                
                @schemas.classproperty
                def POSITIVE_1(cls):
                    return cls("1")
                
                @schemas.classproperty
                def POSITIVE_2(cls):
                    return cls("2")
                
                @schemas.classproperty
                def POSITIVE_3(cls):
                    return cls("3")
                
                @schemas.classproperty
                def POSITIVE_4(cls):
                    return cls("4")
            
            
            class response_code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def POSITIVE_0000(cls):
                    return cls("0000")
                
                @schemas.classproperty
                def _00N7(cls):
                    return cls("00N7")
                
                @schemas.classproperty
                def POSITIVE_0100(cls):
                    return cls("0100")
                
                @schemas.classproperty
                def POSITIVE_0390(cls):
                    return cls("0390")
                
                @schemas.classproperty
                def POSITIVE_0500(cls):
                    return cls("0500")
                
                @schemas.classproperty
                def POSITIVE_0580(cls):
                    return cls("0580")
                
                @schemas.classproperty
                def POSITIVE_0800(cls):
                    return cls("0800")
                
                @schemas.classproperty
                def POSITIVE_0880(cls):
                    return cls("0880")
                
                @schemas.classproperty
                def POSITIVE_0890(cls):
                    return cls("0890")
                
                @schemas.classproperty
                def POSITIVE_0960(cls):
                    return cls("0960")
                
                @schemas.classproperty
                def _0R00(cls):
                    return cls("0R00")
                
                @schemas.classproperty
                def POSITIVE_1000(cls):
                    return cls("1000")
                
                @schemas.classproperty
                def _10BR(cls):
                    return cls("10BR")
                
                @schemas.classproperty
                def POSITIVE_1300(cls):
                    return cls("1300")
                
                @schemas.classproperty
                def POSITIVE_1310(cls):
                    return cls("1310")
                
                @schemas.classproperty
                def POSITIVE_1312(cls):
                    return cls("1312")
                
                @schemas.classproperty
                def POSITIVE_1317(cls):
                    return cls("1317")
                
                @schemas.classproperty
                def POSITIVE_1320(cls):
                    return cls("1320")
                
                @schemas.classproperty
                def POSITIVE_1330(cls):
                    return cls("1330")
                
                @schemas.classproperty
                def POSITIVE_1335(cls):
                    return cls("1335")
                
                @schemas.classproperty
                def POSITIVE_1340(cls):
                    return cls("1340")
                
                @schemas.classproperty
                def POSITIVE_1350(cls):
                    return cls("1350")
                
                @schemas.classproperty
                def POSITIVE_1352(cls):
                    return cls("1352")
                
                @schemas.classproperty
                def POSITIVE_1360(cls):
                    return cls("1360")
                
                @schemas.classproperty
                def POSITIVE_1370(cls):
                    return cls("1370")
                
                @schemas.classproperty
                def POSITIVE_1380(cls):
                    return cls("1380")
                
                @schemas.classproperty
                def POSITIVE_1382(cls):
                    return cls("1382")
                
                @schemas.classproperty
                def POSITIVE_1384(cls):
                    return cls("1384")
                
                @schemas.classproperty
                def POSITIVE_1390(cls):
                    return cls("1390")
                
                @schemas.classproperty
                def POSITIVE_1393(cls):
                    return cls("1393")
                
                @schemas.classproperty
                def POSITIVE_5100(cls):
                    return cls("5100")
                
                @schemas.classproperty
                def POSITIVE_5110(cls):
                    return cls("5110")
                
                @schemas.classproperty
                def POSITIVE_5120(cls):
                    return cls("5120")
                
                @schemas.classproperty
                def POSITIVE_5130(cls):
                    return cls("5130")
                
                @schemas.classproperty
                def POSITIVE_5135(cls):
                    return cls("5135")
                
                @schemas.classproperty
                def POSITIVE_5140(cls):
                    return cls("5140")
                
                @schemas.classproperty
                def POSITIVE_5150(cls):
                    return cls("5150")
                
                @schemas.classproperty
                def POSITIVE_5160(cls):
                    return cls("5160")
                
                @schemas.classproperty
                def POSITIVE_5170(cls):
                    return cls("5170")
                
                @schemas.classproperty
                def POSITIVE_5180(cls):
                    return cls("5180")
                
                @schemas.classproperty
                def POSITIVE_5190(cls):
                    return cls("5190")
                
                @schemas.classproperty
                def POSITIVE_5200(cls):
                    return cls("5200")
                
                @schemas.classproperty
                def POSITIVE_5210(cls):
                    return cls("5210")
                
                @schemas.classproperty
                def POSITIVE_5400(cls):
                    return cls("5400")
                
                @schemas.classproperty
                def POSITIVE_5500(cls):
                    return cls("5500")
                
                @schemas.classproperty
                def POSITIVE_5650(cls):
                    return cls("5650")
                
                @schemas.classproperty
                def POSITIVE_5700(cls):
                    return cls("5700")
                
                @schemas.classproperty
                def POSITIVE_5710(cls):
                    return cls("5710")
                
                @schemas.classproperty
                def POSITIVE_5800(cls):
                    return cls("5800")
                
                @schemas.classproperty
                def POSITIVE_5900(cls):
                    return cls("5900")
                
                @schemas.classproperty
                def POSITIVE_5910(cls):
                    return cls("5910")
                
                @schemas.classproperty
                def POSITIVE_5920(cls):
                    return cls("5920")
                
                @schemas.classproperty
                def POSITIVE_5930(cls):
                    return cls("5930")
                
                @schemas.classproperty
                def POSITIVE_5950(cls):
                    return cls("5950")
                
                @schemas.classproperty
                def POSITIVE_6300(cls):
                    return cls("6300")
                
                @schemas.classproperty
                def POSITIVE_7600(cls):
                    return cls("7600")
                
                @schemas.classproperty
                def POSITIVE_7700(cls):
                    return cls("7700")
                
                @schemas.classproperty
                def POSITIVE_7710(cls):
                    return cls("7710")
                
                @schemas.classproperty
                def POSITIVE_7800(cls):
                    return cls("7800")
                
                @schemas.classproperty
                def POSITIVE_7900(cls):
                    return cls("7900")
                
                @schemas.classproperty
                def POSITIVE_8000(cls):
                    return cls("8000")
                
                @schemas.classproperty
                def POSITIVE_8010(cls):
                    return cls("8010")
                
                @schemas.classproperty
                def POSITIVE_8020(cls):
                    return cls("8020")
                
                @schemas.classproperty
                def POSITIVE_8030(cls):
                    return cls("8030")
                
                @schemas.classproperty
                def POSITIVE_8100(cls):
                    return cls("8100")
                
                @schemas.classproperty
                def POSITIVE_8110(cls):
                    return cls("8110")
                
                @schemas.classproperty
                def POSITIVE_8220(cls):
                    return cls("8220")
                
                @schemas.classproperty
                def POSITIVE_9100(cls):
                    return cls("9100")
                
                @schemas.classproperty
                def POSITIVE_9500(cls):
                    return cls("9500")
                
                @schemas.classproperty
                def POSITIVE_9510(cls):
                    return cls("9510")
                
                @schemas.classproperty
                def POSITIVE_9520(cls):
                    return cls("9520")
                
                @schemas.classproperty
                def POSITIVE_9530(cls):
                    return cls("9530")
                
                @schemas.classproperty
                def POSITIVE_9540(cls):
                    return cls("9540")
                
                @schemas.classproperty
                def POSITIVE_9600(cls):
                    return cls("9600")
                
                @schemas.classproperty
                def PCNR(cls):
                    return cls("PCNR")
                
                @schemas.classproperty
                def PCVV(cls):
                    return cls("PCVV")
                
                @schemas.classproperty
                def PP06(cls):
                    return cls("PP06")
                
                @schemas.classproperty
                def PPRN(cls):
                    return cls("PPRN")
                
                @schemas.classproperty
                def PPAD(cls):
                    return cls("PPAD")
                
                @schemas.classproperty
                def PPAB(cls):
                    return cls("PPAB")
                
                @schemas.classproperty
                def PPAE(cls):
                    return cls("PPAE")
                
                @schemas.classproperty
                def PPAG(cls):
                    return cls("PPAG")
                
                @schemas.classproperty
                def PPAI(cls):
                    return cls("PPAI")
                
                @schemas.classproperty
                def PPAR(cls):
                    return cls("PPAR")
                
                @schemas.classproperty
                def PPAU(cls):
                    return cls("PPAU")
                
                @schemas.classproperty
                def PPAV(cls):
                    return cls("PPAV")
                
                @schemas.classproperty
                def PPAX(cls):
                    return cls("PPAX")
                
                @schemas.classproperty
                def PPBG(cls):
                    return cls("PPBG")
                
                @schemas.classproperty
                def PPC2(cls):
                    return cls("PPC2")
                
                @schemas.classproperty
                def PPCE(cls):
                    return cls("PPCE")
                
                @schemas.classproperty
                def PPCO(cls):
                    return cls("PPCO")
                
                @schemas.classproperty
                def PPCR(cls):
                    return cls("PPCR")
                
                @schemas.classproperty
                def PPCT(cls):
                    return cls("PPCT")
                
                @schemas.classproperty
                def PPCU(cls):
                    return cls("PPCU")
                
                @schemas.classproperty
                def PPD3(cls):
                    return cls("PPD3")
                
                @schemas.classproperty
                def PPDC(cls):
                    return cls("PPDC")
                
                @schemas.classproperty
                def PPDI(cls):
                    return cls("PPDI")
                
                @schemas.classproperty
                def PPDV(cls):
                    return cls("PPDV")
                
                @schemas.classproperty
                def PPDT(cls):
                    return cls("PPDT")
                
                @schemas.classproperty
                def PPEF(cls):
                    return cls("PPEF")
                
                @schemas.classproperty
                def PPEL(cls):
                    return cls("PPEL")
                
                @schemas.classproperty
                def PPER(cls):
                    return cls("PPER")
                
                @schemas.classproperty
                def PPEX(cls):
                    return cls("PPEX")
                
                @schemas.classproperty
                def PPFE(cls):
                    return cls("PPFE")
                
                @schemas.classproperty
                def PPFI(cls):
                    return cls("PPFI")
                
                @schemas.classproperty
                def PPFR(cls):
                    return cls("PPFR")
                
                @schemas.classproperty
                def PPFV(cls):
                    return cls("PPFV")
                
                @schemas.classproperty
                def PPGR(cls):
                    return cls("PPGR")
                
                @schemas.classproperty
                def PPH1(cls):
                    return cls("PPH1")
                
                @schemas.classproperty
                def PPIF(cls):
                    return cls("PPIF")
                
                @schemas.classproperty
                def PPII(cls):
                    return cls("PPII")
                
                @schemas.classproperty
                def PPIM(cls):
                    return cls("PPIM")
                
                @schemas.classproperty
                def PPIT(cls):
                    return cls("PPIT")
                
                @schemas.classproperty
                def PPLR(cls):
                    return cls("PPLR")
                
                @schemas.classproperty
                def PPLS(cls):
                    return cls("PPLS")
                
                @schemas.classproperty
                def PPMB(cls):
                    return cls("PPMB")
                
                @schemas.classproperty
                def PPMC(cls):
                    return cls("PPMC")
                
                @schemas.classproperty
                def PPMD(cls):
                    return cls("PPMD")
                
                @schemas.classproperty
                def PPNC(cls):
                    return cls("PPNC")
                
                @schemas.classproperty
                def PPNL(cls):
                    return cls("PPNL")
                
                @schemas.classproperty
                def PPNM(cls):
                    return cls("PPNM")
                
                @schemas.classproperty
                def PPNT(cls):
                    return cls("PPNT")
                
                @schemas.classproperty
                def PPPH(cls):
                    return cls("PPPH")
                
                @schemas.classproperty
                def PPPI(cls):
                    return cls("PPPI")
                
                @schemas.classproperty
                def PPPM(cls):
                    return cls("PPPM")
                
                @schemas.classproperty
                def PPQC(cls):
                    return cls("PPQC")
                
                @schemas.classproperty
                def PPRE(cls):
                    return cls("PPRE")
                
                @schemas.classproperty
                def PPRF(cls):
                    return cls("PPRF")
                
                @schemas.classproperty
                def PPRR(cls):
                    return cls("PPRR")
                
                @schemas.classproperty
                def PPS0(cls):
                    return cls("PPS0")
                
                @schemas.classproperty
                def PPS1(cls):
                    return cls("PPS1")
                
                @schemas.classproperty
                def PPS2(cls):
                    return cls("PPS2")
                
                @schemas.classproperty
                def PPS3(cls):
                    return cls("PPS3")
                
                @schemas.classproperty
                def PPS4(cls):
                    return cls("PPS4")
                
                @schemas.classproperty
                def PPS5(cls):
                    return cls("PPS5")
                
                @schemas.classproperty
                def PPS6(cls):
                    return cls("PPS6")
                
                @schemas.classproperty
                def PPSC(cls):
                    return cls("PPSC")
                
                @schemas.classproperty
                def PPSD(cls):
                    return cls("PPSD")
                
                @schemas.classproperty
                def PPSE(cls):
                    return cls("PPSE")
                
                @schemas.classproperty
                def PPTE(cls):
                    return cls("PPTE")
                
                @schemas.classproperty
                def PPTF(cls):
                    return cls("PPTF")
                
                @schemas.classproperty
                def PPTI(cls):
                    return cls("PPTI")
                
                @schemas.classproperty
                def PPTR(cls):
                    return cls("PPTR")
                
                @schemas.classproperty
                def PPTT(cls):
                    return cls("PPTT")
                
                @schemas.classproperty
                def PPTV(cls):
                    return cls("PPTV")
                
                @schemas.classproperty
                def PPUA(cls):
                    return cls("PPUA")
                
                @schemas.classproperty
                def PPUC(cls):
                    return cls("PPUC")
                
                @schemas.classproperty
                def PPUE(cls):
                    return cls("PPUE")
                
                @schemas.classproperty
                def PPUI(cls):
                    return cls("PPUI")
                
                @schemas.classproperty
                def PPUP(cls):
                    return cls("PPUP")
                
                @schemas.classproperty
                def PPUR(cls):
                    return cls("PPUR")
                
                @schemas.classproperty
                def PPVC(cls):
                    return cls("PPVC")
                
                @schemas.classproperty
                def PPVE(cls):
                    return cls("PPVE")
                
                @schemas.classproperty
                def PPVT(cls):
                    return cls("PPVT")
            
            
            class payment_advice_code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def POSITIVE_01(cls):
                    return cls("01")
                
                @schemas.classproperty
                def POSITIVE_02(cls):
                    return cls("02")
                
                @schemas.classproperty
                def POSITIVE_03(cls):
                    return cls("03")
                
                @schemas.classproperty
                def POSITIVE_21(cls):
                    return cls("21")
            __annotations__ = {
                "avs_code": avs_code,
                "cvv_code": cvv_code,
                "response_code": response_code,
                "payment_advice_code": payment_advice_code,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avs_code"]) -> MetaOapg.properties.avs_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvv_code"]) -> MetaOapg.properties.cvv_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["response_code"]) -> MetaOapg.properties.response_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payment_advice_code"]) -> MetaOapg.properties.payment_advice_code: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["avs_code", "cvv_code", "response_code", "payment_advice_code", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avs_code"]) -> typing.Union[MetaOapg.properties.avs_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvv_code"]) -> typing.Union[MetaOapg.properties.cvv_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["response_code"]) -> typing.Union[MetaOapg.properties.response_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payment_advice_code"]) -> typing.Union[MetaOapg.properties.payment_advice_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["avs_code", "cvv_code", "response_code", "payment_advice_code", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        avs_code: typing.Union[MetaOapg.properties.avs_code, str, schemas.Unset] = schemas.unset,
        cvv_code: typing.Union[MetaOapg.properties.cvv_code, str, schemas.Unset] = schemas.unset,
        response_code: typing.Union[MetaOapg.properties.response_code, str, schemas.Unset] = schemas.unset,
        payment_advice_code: typing.Union[MetaOapg.properties.payment_advice_code, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProcessorResponse':
        return super().__new__(
            cls,
            *args,
            avs_code=avs_code,
            cvv_code=cvv_code,
            response_code=response_code,
            payment_advice_code=payment_advice_code,
            _configuration=_configuration,
            **kwargs,
        )
