# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_payment_python_sdk import schemas  # noqa: F401


class SellerProtection(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The level of protection offered as defined by [PayPal Seller Protection for Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection).
    """


    class MetaOapg:
        
        class properties:
            
            
            class status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ELIGIBLE": "ELIGIBLE",
                        "PARTIALLY_ELIGIBLE": "PARTIALLY_ELIGIBLE",
                        "NOT_ELIGIBLE": "NOT_ELIGIBLE",
                    }
                
                @schemas.classproperty
                def ELIGIBLE(cls):
                    return cls("ELIGIBLE")
                
                @schemas.classproperty
                def PARTIALLY_ELIGIBLE(cls):
                    return cls("PARTIALLY_ELIGIBLE")
                
                @schemas.classproperty
                def NOT_ELIGIBLE(cls):
                    return cls("NOT_ELIGIBLE")
        
            @staticmethod
            def dispute_categories() -> typing.Type['SellerProtectionDisputeCategories']:
                return SellerProtectionDisputeCategories
            __annotations__ = {
                "status": status,
                "dispute_categories": dispute_categories,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dispute_categories"]) -> 'SellerProtectionDisputeCategories': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["status", "dispute_categories", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dispute_categories"]) -> typing.Union['SellerProtectionDisputeCategories', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["status", "dispute_categories", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        dispute_categories: typing.Union['SellerProtectionDisputeCategories', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SellerProtection':
        return super().__new__(
            cls,
            *args,
            status=status,
            dispute_categories=dispute_categories,
            _configuration=_configuration,
            **kwargs,
        )

from pay_pal_payment_python_sdk.model.seller_protection_dispute_categories import SellerProtectionDisputeCategories
