# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class RelatedIds(BaseModel):
    # Order ID related to the resource.
    order_id: typing.Optional[str] = Field(None, alias='order_id')

    # Authorization ID related to the resource.
    authorization_id: typing.Optional[str] = Field(None, alias='authorization_id')

    # Capture ID related to the resource.
    capture_id: typing.Optional[str] = Field(None, alias='capture_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
