# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import pay_pal_payment_python_sdk
from pay_pal_payment_python_sdk.paths.v2_payments_authorizations_authorization_id_reauthorize import post
from pay_pal_payment_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV2PaymentsAuthorizationsAuthorizationIdReauthorize(ApiTestMixin, unittest.TestCase):
    """
    V2PaymentsAuthorizationsAuthorizationIdReauthorize unit test stubs
        Reauthorize authorized payment
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
