# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

import unittest

import pay_pal_payment_python_sdk
from pay_pal_payment_python_sdk.model.error400 import Error400
from pay_pal_payment_python_sdk import configuration


class TestError400(unittest.TestCase):
    """Error400 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
