# coding: utf-8
"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from pay_pal_payment_python_sdk.client_custom import ClientCustom
from pay_pal_payment_python_sdk.configuration import Configuration
from pay_pal_payment_python_sdk.api_client import ApiClient
from pay_pal_payment_python_sdk.type_util import copy_signature
from pay_pal_payment_python_sdk.apis.tags.authorizations_api import AuthorizationsApi
from pay_pal_payment_python_sdk.apis.tags.captures_api import CapturesApi
from pay_pal_payment_python_sdk.apis.tags.refunds_api import RefundsApi



class PayPalPayment(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.authorizations: AuthorizationsApi = AuthorizationsApi(api_client)
        self.captures: CapturesApi = CapturesApi(api_client)
        self.refunds: RefundsApi = RefundsApi(api_client)
