# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_payment_python_sdk.type.error_details import ErrorDetails
from pay_pal_payment_python_sdk.type.error_link_description import ErrorLinkDescription

class RequiredError400(TypedDict):
    pass

class OptionalError400(TypedDict, total=False):
    name: str

    message: str

    details: typing.List[ErrorDetails]

    # The PayPal internal ID. Used for correlation purposes.
    debug_id: str

    # An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
    links: typing.List[ErrorLinkDescription]

class Error400(RequiredError400, OptionalError400):
    pass
