# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_payment_python_sdk.type.error_location import ErrorLocation

class RequiredErrorDetails(TypedDict):
    # The unique, fine-grained application-level error code.
    issue: str

class OptionalErrorDetails(TypedDict, total=False):
    # The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
    description: str

    # The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors.
    field: str

    # The value of the field that caused the error.
    value: str

    location: ErrorLocation

class ErrorDetails(RequiredErrorDetails, OptionalErrorDetails):
    pass
