# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProcessorResponse(TypedDict):
    pass

class OptionalProcessorResponse(TypedDict, total=False):
    # The address verification code for Visa, Discover, Mastercard, or American Express transactions.
    avs_code: str

    # The card verification value code for for Visa, Discover, Mastercard, or American Express.
    cvv_code: str

    # Processor response code for the non-PayPal payment processor errors.
    response_code: str

    # The declined payment transactions might have payment advice codes. The card networks, like Visa and Mastercard, return payment advice codes.
    payment_advice_code: str

class ProcessorResponse(RequiredProcessorResponse, OptionalProcessorResponse):
    pass
