# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_payment_python_sdk.type.refund_status_details import RefundStatusDetails

class RequiredRefundStatus(TypedDict):
    pass

class OptionalRefundStatus(TypedDict, total=False):
    # The status of the refund.
    status: str

    status_details: RefundStatusDetails

class RefundStatus(RequiredRefundStatus, OptionalRefundStatus):
    pass
