# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_payment_python_sdk.type.money import Money
from pay_pal_payment_python_sdk.type.payment_instruction2 import PaymentInstruction2

class RequiredRefundRequest(TypedDict):
    pass

class OptionalRefundRequest(TypedDict, total=False):
    amount: Money

    # The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports. The pattern is defined by an external party and supports Unicode.
    custom_id: str

    # The API caller-provided external invoice ID for this order. The pattern is defined by an external party and supports Unicode.
    invoice_id: str

    # The reason for the refund. Appears in both the payer's transaction history and the emails that the payer receives. The pattern is defined by an external party and supports Unicode.
    note_to_payer: str

    payment_instruction: PaymentInstruction2

class RefundRequest(RequiredRefundRequest, OptionalRefundRequest):
    pass
