# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRelatedIds(TypedDict):
    pass

class OptionalRelatedIds(TypedDict, total=False):
    # Order ID related to the resource.
    order_id: str

    # Authorization ID related to the resource.
    authorization_id: str

    # Capture ID related to the resource.
    capture_id: str

class RelatedIds(RequiredRelatedIds, OptionalRelatedIds):
    pass
