# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSupplementaryPurchaseData(TypedDict):
    pass

class OptionalSupplementaryPurchaseData(TypedDict, total=False):
    # The API caller-provided external invoice number for this order. Appears in both the payer's transaction history and the emails that the payer receives.
    invoice_id: str

    # An informational note about this settlement. Appears in both the payer's transaction history and the emails that the payer receives.
    note_to_payer: str

class SupplementaryPurchaseData(RequiredSupplementaryPurchaseData, OptionalSupplementaryPurchaseData):
    pass
