# coding: utf-8

"""
    Payments

    Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.

    The version of the OpenAPI document: 2.5
    Generated by: https://konfigthis.com
"""

from pay_pal_payment_python_sdk.paths.v2_payments_captures_capture_id_refund.post import RefundPayment
from pay_pal_payment_python_sdk.paths.v2_payments_captures_capture_id.get import ShowDetails
from pay_pal_payment_python_sdk.apis.tags.captures_api_raw import CapturesApiRaw


class CapturesApi(
    RefundPayment,
    ShowDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CapturesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CapturesApiRaw(api_client)
